# Site settings
title: Staying Startup Cool
email: jesstuan@gmail.com
description: made by yay puppy
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jtuanjones
github_username: jessicatuan

# Build settings
markdown: kramdown
permalink: pretty
